Repository DeveloperAcademy-POSTECH/MC2-Team5-Firefighter, pull requests merged in 2023-08, with the labels that each got.

#482 [REFACTOR] 방생성 관련 뷰 , 뷰컨트롤러를 분리하였습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
  Manito/Manito/Screens/ChooseCharacter/View/ChooseCharacterView.swift
  Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/CharacterCollectionView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/CheckRoomInfoView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/InputCapacityView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/InputDateView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/InputTitleView.swift
  Manito/Manito/Screens/CreateRoom/View/CreateRoomView.swift
  Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
Labels: ▪️ Create Room, 🔨 Refactor, 👾 호야, ▪️ Character-choose

#485 [FEAT] Build Configuration에 따라서 baseURL과 GoogleService 파일이 다르게 빌드되도록 구현했습니다.
  .github/workflows/XCTestBuild.yml
  .github/workflows/build.yml
  Manito/Configuration/Dev/Dev.xcconfig
  Manito/Configuration/Dev/GoogleService-Info-Dev.plist
  Manito/Configuration/Prod/GoogleService-Info-Prod.plist
  Manito/Configuration/Prod/Prod.xcconfig
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito.xcodeproj/xcshareddata/xcschemes/Manito-Dev.xcscheme
  Manito/Manito.xcodeproj/xcshareddata/xcschemes/Manito-Prod.xcscheme
  Manito/Manito/Global/Literal/URLLiteral.swift
  Manito/Manito/Network/Foundation/APIEnvironment.swift
  Manito/Packages/MTNetwork/.swiftpm/xcode/xcshareddata/xcschemes/MTNetworkTests.xcscheme
Labels: ⚙️ Setting, 👾 듀나

#487 [FIX] LetterViewController 부분에서 발생하는 메모리 릭 문제를 해결했습니다.
  Manito/Manito/Screens/Letter/Views/UIComponents/LetterHeaderView.swift
  Manito/Manito/Screens/Letter/Views/Views/LetterView.swift
Labels: 🐞 Bugfix, ▪️ Letter, 👾 듀나

#489 [CHORE] wait 시간 2초에서 5초로 수정
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/ManitoTests/DetailWaitViewModelTest.swift
  Manito/ManitoTests/ManitoTests.swift
Labels: 👾 케미, 🙏 ASAP, 🛠 Chore

#496 [DEL] auto-assign.yml 파일 멤버를 수정했습니다.
  .github/auto_assign.yml
Labels: 📖 Docs, 👾 듀나, 🛠 Chore

#498 [BUGFIX] 시작날짜가 오늘임에도 '시작 날짜 지남' Alert뜨는 에러를 해결했습니다.
  Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
Labels: 🐞 Bugfix, ▪️ Detail-wait, 👾 케미

#503 [FEAT] 회원탈퇴 api 연결을 진행했습니다.
  Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Manito/Manito/Data/Network/EndPoint/SettingEndPoint.swift
  Manito/Manito/Data/Repository/SettingRepository.swift
  Manito/Manito/Global/Literal/TextLiteral.swift
  Manito/Manito/Global/Supports/SceneDelegate.swift
  Manito/Manito/Screens/CreateNickName/CreateNickNameViewController.swift
  Manito/Manito/Screens/Login/LoginViewController.swift
  Manito/Manito/Screens/Setting/SettingViewController.swift
Labels: 👾 호야, ▪️ Settings, ✨ Feature, 🙏 ASAP
