Repository DeveloperAcademy-POSTECH/MC2-Team5-Firefighter, pull requests merged in 2023-09, with the labels that each got.

#502 [CHORE] Letter Screen의 파일을 새로운 폴더로 옮기고 Letter에서 사용하는 DTO, Entity를 수정했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Data/DTO/Response/LetterDTO.swift
  Manito/Manito/Data/DTO/Response/MessageListItemDTO.swift
  Manito/Manito/Data/DTO/Response/RoomInfoDTO.swift
  Manito/Manito/Data/DTO/Response/UserInfoDTO.swift
  Manito/Manito/Domain/Entity/MessageListItem.swift
  Manito/Manito/Domain/Usecase/LetterScene/LetterUsecase.swift
  Manito/Manito/Global/Error/Presentation/LetterScene/LetterImageError.swift
  Manito/Manito/Presentation/Scene/LetterScene/View/Cell/LetterCollectionViewCell.swift
  Manito/Manito/Presentation/Scene/LetterScene/View/LetterView.swift
  Manito/Manito/Presentation/Scene/LetterScene/View/UIComponent/LetterHeaderView.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewController/LetterViewController.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewModel/LetterViewModel.swift
  Manito/Manito/Screens/Detail-Ing/DetailingViewController.swift
Labels: 📖 Docs, ▪️ Letter, 🔨 Refactor, 👾 듀나

#512 [MOVE] App 폴더로 Supports 폴더 내부 파일들을 옮겼습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/App/AppDelegate.swift
  Manito/Manito/App/Info.plist
  Manito/Manito/App/Manito.entitlements
  Manito/Manito/App/SceneDelegate.swift
Labels: ⚙️ Setting, 👾 듀나, 🛠 Chore

#504 [CHORE] 전체적인 Entity 수정에 따라 TestCI 실패하던 문제를 해결했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Data/DTO/Response/RoomInfoDTO.swift
  Manito/Manito/Data/DTO/Response/UserInfoDTO.swift
  Manito/Manito/Domain/Entity/IndividualMission.swift
  Manito/Manito/Domain/Entity/InvitationCode.swift
  Manito/Manito/Domain/Entity/MessageCountInfo.swift
  Manito/Manito/Domain/Entity/ParticipantList.swift
  Manito/Manito/Domain/Entity/RoomInfo.swift
  Manito/Manito/Domain/Entity/RoomListItem.swift
  Manito/Manito/Domain/Entity/UserInfo.swift
  Manito/Manito/Screens/Detail-Ing/View/DetailingView.swift
  Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
  Manito/Manito/Screens/Detail-Wait/ViewModel/DetailWaitViewModel.swift
  Manito/ManitoTests/Presentation/DetailWait/Service/MockDetailWaitService.swift
  Manito/ManitoTests/Presentation/DetailWait/ViewModel/DetailWaitViewModelTest.swift
Labels: 👾 케미, 🛠 Chore

#506 [REFACTOR] SettingViewController 를 MVVM + Combine 으로 리팩토링 했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Screens/ChangeNickname/ChangeNickNameViewController.swift
  Manito/Manito/Screens/Main/MainViewController.swift
  Manito/Manito/Screens/Setting/Service/SettingService.swift
  Manito/Manito/Screens/Setting/SettingViewController.swift
  Manito/Manito/Screens/Setting/UIComponent/TopCharacterImageView.swift
  Manito/Manito/Screens/Setting/View/SettingView.swift
  Manito/Manito/Screens/Setting/ViewControllers/SettingViewController+MailComposeViewControllerDelegate.swift
  Manito/Manito/Screens/Setting/ViewControllers/SettingViewController.swift
  Manito/Manito/Screens/Setting/ViewModel/SettingViewModel.swift
Labels: 🔨 Refactor, 👾 호야, ▪️ Settings

#510 [CHORE] 방 상태를 RoomStatus Enum 타입으로 사용할 수 있도록 수정했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Manito/Manito/Data/DTO/Response/RoomListDTO.swift
  Manito/Manito/Domain/Entity/RoomInfo.swift
  Manito/Manito/Domain/Entity/RoomListItem.swift
  Manito/Manito/Domain/Entity/RoomStatus.swift
  Manito/Manito/Screens/Detail-Ing/View/DetailingView.swift
  Manito/Manito/Screens/Detail-Wait/UIComponent/DetailWaitTitleView.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
  Manito/Manito/Screens/Main/MainViewController.swift
Labels: 🔨 Refactor, 👾 듀나, 🛠 Chore

#515 [CHORE] BaseViewType 프로토콜을 생성하여 기본적인 메서드를 정리했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Global/Base/BaseCollectionViewCell.swift
  Manito/Manito/Global/Base/BaseTableViewCell.swift
  Manito/Manito/Presentation/Common/Base/BaseViewController.swift
  Manito/Manito/Presentation/Common/Base/BaseViewControllerType.swift
  Manito/Manito/Presentation/Common/Base/BaseViewModelType.swift
  Manito/Manito/Presentation/Common/Base/BaseViewType.swift
  Manito/Manito/Presentation/Scene/LetterScene/View/Cell/LetterCollectionViewCell.swift
  Manito/Manito/Presentation/Scene/LetterScene/View/LetterView.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewController/LetterViewController.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewModel/LetterViewModel.swift
  Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
  Manito/Manito/Screens/ChooseCharacter/UIComponent/CharacterCollectionViewCell.swift
  Manito/Manito/Screens/ChooseCharacter/View/ChooseCharacterView.swift
  Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
  Manito/Manito/Screens/CreateRoom/View/CreateRoomView.swift
  Manito/Manito/Screens/CreateRoom/ViewModel/CreateRoomViewModel.swift
  Manito/Manito/Screens/Detail-Ing/Cell/MemoryCollectionViewCell.swift
  Manito/Manito/Screens/Detail-Ing/FriendListViewController.swift
  Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
  Manito/Manito/Screens/Detail-Ing/MissionEditViewController.swift
  Manito/Manito/Screens/Detail-Ing/View/DetailingView.swift
  Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailEditView.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
  Manito/Manito/Screens/Interaction/Cell/OpenManittoCollectionViewCell.swift
  Manito/Manito/Screens/Interaction/SelectManitteeViewController.swift
  Manito/Manito/Screens/Interaction/View/OpenManittoView.swift
  Manito/Manito/Screens/Interaction/View/SelectManitteeView.swift
  Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
  Manito/Manito/Screens/Letter/Views/ViewControllers/CreateLetterViewController.swift
  Manito/Manito/Screens/Letter/Views/Views/CreateLetterView.swift
  Manito/Manito/Screens/Letter/Views/Views/LetterImageView.swift
  Manito/Manito/Screens/Login/LoginViewController.swift
  Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
  Manito/Manito/Screens/Main/Cell/ManitoRoomCollectionCell.swift
  Manito/Manito/Screens/Main/MainViewController.swift
  Manito/Manito/Screens/NickName/View/NicknameView.swift
  Manito/Manito/Screens/ParticipateRoom/ParticipateRoomView.swift
  Manito/Manito/Screens/Setting/View/SettingView.swift
  Manito/Manito/Screens/SettingDeveloperInfo/Cell/DeveloperInfoViewCell.swift
  Manito/Manito/Screens/SettingDeveloperInfo/SettingDeveloperInfoViewController.swift
  Manito/Manito/Screens/Splash/SplashViewController.swift
Labels: 🔨 Refactor, 👾 듀나

#517 [CHORE] Extension, Util 파일을 정리했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Domain/Entity/Character.swift
  Manito/Manito/Global/Extension/Encodable+Extension.swift
  Manito/Manito/Global/Extension/UITableView+Extension.swift
  Manito/Manito/Service/ImageCacheManager/ImageCacheManager.swift
  Manito/Manito/Util/Extension/Combine/Publisher+Async.swift
  Manito/Manito/Util/Extension/Combine/UIControl+Combine.swift
  Manito/Manito/Util/Extension/Combine/UIScrollView+Combine.swift
  Manito/Manito/Util/Extension/Combine/UIViewController+Combine.swift
  Manito/Manito/Util/Extension/Type/Date+Extension.swift
  Manito/Manito/Util/Extension/Type/Int+RandomNumber.swift
  Manito/Manito/Util/Extension/Type/NSObject+ClassName.swift
  Manito/Manito/Util/Extension/Type/Notification+Extension.swift
  Manito/Manito/Util/Extension/Type/String+Date.swift
  Manito/Manito/Util/Extension/UI/UIColor+Extension.swift
  Manito/Manito/Util/Extension/UI/UIFont+Extension.swift
  Manito/Manito/Util/Extension/UI/UIView/UIButton+Extension.swift
  Manito/Manito/Util/Extension/UI/UIView/UICollectionView+Extension.swift
  Manito/Manito/Util/Extension/UI/UIView/UIImageView+Cache.swift
  Manito/Manito/Util/Extension/UI/UIView/UILabel+Extension.swift
  Manito/Manito/Util/Extension/UI/UIView/UIView+Extension.swift
  Manito/Manito/Util/Extension/UI/UIViewController/UIViewController+Alert.swift
  Manito/Manito/Util/Extension/UI/UIViewController/UIViewController+Keyboard.swift
  Manito/Manito/Util/Literal/ImageLiteral.swift
  Manito/Manito/Util/Literal/SizeLiteral.swift
  Manito/Manito/Util/Literal/TextLiteral.swift
  Manito/Manito/Util/Literal/URLLiteral.swift
  Manito/Manito/Util/Logger/Logger.swift
Labels: ⚙️ Setting, 👾 듀나, 🛠 Chore

#526 [CHORE] 방 참여시 캐릭터 인덱스가 설정 안되는 문제를 수정했습니다.
  Manito/Manito/Screens/ChooseCharacter/View/ChooseCharacterView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/CharacterCollectionView.swift
Labels: 👾 케미, 🙏 ASAP, 🛠 Chore

#523 [CHORE] Character Type 네이밍 수정 및 내부 코드 정리를 진행했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Domain/Entity/Character.swift
  Manito/Manito/Domain/Entity/DefaultCharacterType.swift
  Manito/Manito/Domain/Entity/RoomStatus.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/CharacterCollectionView.swift
  Manito/Manito/Screens/Detail-Ing/Cell/FriendCollectionViewCell.swift
  Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
  Manito/Manito/Screens/Interaction/Cell/OpenManittoCollectionViewCell.swift
Labels: 👾 듀나, 🛠 Chore

#521 [REFACTOR] ParticipateRoomVC 와 CheckRoomVC 를 MVVM + Combine 으로 리팩토링 했습니다...
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Data/DTO/Response/ParticipatedRoomInfoDTO.swift
  Manito/Manito/Domain/Entity/ParticipatedRoomInfo.swift
  Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
  Manito/Manito/Screens/CheckRoom/UIComponent/PeopleInfoView.swift
  Manito/Manito/Screens/CheckRoom/UIComponent/RoomInfoView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/CheckRoomInfoView.swift
  Manito/Manito/Screens/Main/MainViewController.swift
  Manito/Manito/Screens/ParticipateRoom/ParticipateRoomViewController.swift
  Manito/Manito/Screens/ParticipateRoom/Services/ParticipateRoomService.swift
  Manito/Manito/Screens/ParticipateRoom/UIComponent/InputInvitedCodeView.swift
  Manito/Manito/Screens/ParticipateRoom/View/ParticipateRoomView.swift
  Manito/Manito/Screens/ParticipateRoom/View/ParticipationRoomDetailsView.swift
  Manito/Manito/Screens/ParticipateRoom/ViewControllers/ParticipateRoomViewController.swift
  Manito/Manito/Screens/ParticipateRoom/ViewControllers/ParticipationRoomDetailsViewController.swift
  Manito/Manito/Screens/ParticipateRoom/ViewModel/ParticipateRoomViewModel.swift
  Manito/Manito/Screens/ParticipateRoom/ViewModel/ParticipationRoomDetailsViewModel.swift
  Manito/Manito/Util/Extension/Type/Notification+Extension.swift
  Manito/Manito/Util/Literal/TextLiteral.swift
Labels: ▪️ Invite Room, 🔨 Refactor, 👾 호야, ▪️ ParticipateRoom

#527 [CHORE] Extension 내부 메서드, 변수를 수정했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Domain/Entity/MessageListItem.swift
  Manito/Manito/Domain/Entity/RoomInfo.swift
  Manito/Manito/Domain/Entity/RoomListItem.swift
  Manito/Manito/Screens/Detail-Ing/View/DetailingView.swift
  Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailEditView.swift
  Manito/Manito/Screens/Interaction/View/OpenManittoPopupView.swift
  Manito/Manito/Util/Extension/Type/Date+Extension.swift
  Manito/Manito/Util/Extension/Type/String+DateFormatter.swift
  Manito/Manito/Util/Extension/UI/UIView/UILabel+Config.swift
  Manito/Manito/Util/Extension/UI/UIView/UIView+Animation.swift
  Manito/Manito/Util/Extension/UI/UIView/UIView+Extension.swift
Labels: 🔨 Refactor, 👾 듀나, 🛠 Chore

#529 [CHORE] Letter에서 사용하는 Error, RoomStatus에 대한 수정 사항을 반영했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Domain/Error/LetterScene/LetterUsecaseError.swift
  Manito/Manito/Domain/Usecase/LetterScene/LetterUsecase.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewController/LetterViewController.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewModel/LetterViewModel.swift
  Manito/Manito/Screens/Detail-Ing/DetailingViewController.swift
Labels: ▪️ Letter, 👾 듀나, 🛠 Chore, 🫶🏻 Improvement

#533 [ADD] 프로젝트에 Resource 파일을 적용했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/App/AppDelegate.swift
  Manito/Manito/Domain/Entity/DefaultCharacterType.swift
  Manito/Manito/Presentation/Common/Component/Button/BackButton.swift
  Manito/Manito/Presentation/Common/Component/Button/MoreButton.swift
  Manito/Manito/Presentation/Common/Component/Button/SettingButton.swift
  Manito/Manito/Presentation/Common/Component/View/GuideView.swift
  Manito/Manito/Presentation/Scene/LetterScene/View/Cell/LetterCollectionViewCell.swift
  Manito/Manito/Resource/Assets.xcassets/imgTextLogo.imageset/Contents.json
  Manito/Manito/Resource/Assets.xcassets/imgTextLogo.imageset/imgTextLogo.png
  Manito/Manito/Resource/Assets.xcassets/imgTextLogo.imageset/imgTextLogo@2x.png
  Manito/Manito/Resource/Assets.xcassets/imgTextLogo.imageset/imgTextLogo@3x.png
  Manito/Manito/Resource/Storyboards/Splash.storyboard
  Manito/Manito/Screens/CheckRoom/CheckRoomViewController.swift
  Manito/Manito/Screens/CheckRoom/UIComponent/PeopleInfoView.swift
  Manito/Manito/Screens/ChooseCharacter/UIComponent/CharacterCollectionViewCell.swift
  Manito/Manito/Screens/ChooseCharacter/View/ChooseCharacterView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/CheckRoomInfoView.swift
  Manito/Manito/Screens/CreateRoom/UIComponent/InputCapacityView.swift
  Manito/Manito/Screens/CreateRoom/View/CreateRoomView.swift
  Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
  Manito/Manito/Screens/Detail-Ing/View/DetailingView.swift
  Manito/Manito/Screens/Detail-Wait/UIComponent/CalendarView.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailEditView.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
  Manito/Manito/Screens/Interaction/View/OpenManittoPopupView.swift
  Manito/Manito/Screens/Interaction/View/SelectManitteeView.swift
  Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
  Manito/Manito/Screens/Letter/Views/UIComponents/CreateLetterPhotoView.swift
  Manito/Manito/Screens/Letter/Views/Views/LetterImageView.swift
  Manito/Manito/Screens/Login/LoginViewController.swift
  Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
  Manito/Manito/Screens/Main/Cell/ManitoRoomCollectionCell.swift
  Manito/Manito/Screens/Main/MainViewController.swift
  Manito/Manito/Screens/Main/UIComponent/CommonMissionView.swift
  Manito/Manito/Screens/ParticipateRoom/ParticipateRoomView.swift
  Manito/Manito/Screens/Setting/UIComponent/TopCharacterImageView.swift
  Manito/Manito/Screens/SettingDeveloperInfo/Cell/DeveloperInfoViewCell.swift
  Manito/Manito/Screens/SettingDeveloperInfo/SettingDeveloperInfoViewController.swift
  Manito/Manito/Screens/SettingDeveloperInfo/UIComponent/SettingDeveloperInfoHeaderView.swift
  Manito/Manito/Screens/Splash/SplashViewController.swift
  Manito/Manito/Util/Literal/GIFSet.swift
  Manito/Modules/MTResource/MTResource.xcodeproj/project.pbxproj
  Manito/Modules/MTResource/MTResource/FontSet.swift
  Manito/Modules/MTResource/MTResource/Foundation/BundleToken.swift
  Manito/Modules/MTResource/MTResource/ImageSet.swift
Labels: ⚙️ Setting, 👾 듀나

#538 [CHORE] ColorSet의 yellow네이밍을 수정합니다.
  Manito/Manito/Screens/Main/Cell/CreateRoomCollectionViewCell.swift
  Manito/Manito/Screens/ParticipateRoom/View/ParticipationRoomDetailsView.swift
  Manito/Modules/MTResource/MTResource/ColorSet.swift
Labels: 👾 케미, 🛠 Chore

#540 [CHORE] v1.6.0 출시에 따라 develop 브랜치를 업데이트 합니다.
  Manito/Manito.xcodeproj/project.pbxproj
Labels: 🛠 Chore

#535 [CHORE] BaseViewController를 상속 -> Protocol로 변경했습니다
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/Manito/Presentation/Common/Base/BaseViewController.swift
  Manito/Manito/Presentation/Common/Base/Keyboardable.swift
  Manito/Manito/Presentation/Common/Base/Navigationable.swift
  Manito/Manito/Presentation/Scene/LetterScene/ViewController/LetterViewController.swift
  Manito/Manito/Screens/ChooseCharacter/ChooseCharacterViewController.swift
  Manito/Manito/Screens/CreateRoom/CreateRoomViewController.swift
  Manito/Manito/Screens/Detail-Ing/DetailingViewController.swift
  Manito/Manito/Screens/Detail-Ing/FriendListViewController.swift
  Manito/Manito/Screens/Detail-Ing/MemoryViewController.swift
  Manito/Manito/Screens/Detail-Ing/MissionEditViewController.swift
  Manito/Manito/Screens/Detail-Wait/DetailEditViewController.swift
  Manito/Manito/Screens/Detail-Wait/DetailWaitViewController.swift
  Manito/Manito/Screens/Interaction/OpenManittoViewController.swift
  Manito/Manito/Screens/Interaction/SelectManitteeViewController.swift
  Manito/Manito/Screens/InvitedCode/InvitedCodeViewController.swift
  Manito/Manito/Screens/Letter/Views/ViewControllers/CreateLetterViewController.swift
  Manito/Manito/Screens/Letter/Views/ViewControllers/LetterImageViewController.swift
  Manito/Manito/Screens/Login/LoginViewController.swift
  Manito/Manito/Screens/Main/MainViewController.swift
  Manito/Manito/Screens/NickName/ViewControllers/ChangeNicknameViewController.swift
  Manito/Manito/Screens/NickName/ViewControllers/CreateNicknameViewController.swift
  Manito/Manito/Screens/ParticipateRoom/ViewControllers/ParticipateRoomViewController.swift
  Manito/Manito/Screens/ParticipateRoom/ViewControllers/ParticipationRoomDetailsViewController.swift
  Manito/Manito/Screens/Setting/ViewControllers/SettingViewController.swift
  Manito/Manito/Screens/SettingDeveloperInfo/SettingDeveloperInfoViewController.swift
  Manito/Manito/Util/Extension/UI/UIViewController/UIViewController+Extension.swift
Labels: 🔨 Refactor, 👾 케미, 👏 Compliment

#542 [CHORE] 방 정보와 관련된 Entity에 설명 주석을 추가했습니다.
  Manito/Manito/Domain/Entity/IndividualMission.swift
  Manito/Manito/Domain/Entity/InvitationCode.swift
  Manito/Manito/Domain/Entity/MessageCountInfo.swift
  Manito/Manito/Domain/Entity/ParticipantList.swift
  Manito/Manito/Domain/Entity/RoomInfo.swift
  Manito/Manito/Domain/Entity/RoomListItem.swift
  Manito/Manito/Domain/Entity/UserInfo.swift
  Manito/Manito/Screens/Detail-Wait/View/DetailWaitView.swift
  Manito/Manito/Util/Extension/Type/Date+Extension.swift
  Manito/Manito/Util/Extension/Type/String+DateFormatter.swift
Labels: 👾 케미, 🛠 Chore

#544 [ADD] 방 정보 관련된 Entity와 Extension에 대한 테스트 코드를 작성했습니다.
  Manito/Manito.xcodeproj/project.pbxproj
  Manito/ManitoTests/Domain/Entity/RoomInfoTest.swift
  Manito/ManitoTests/Domain/Entity/RoomListItemTest.swift
  Manito/ManitoTests/Util/Extension/Type/Date+ExtensionTest.swift
Labels: 👾 케미, 🛠 Chore
